name: Keep Supabase Awake

on:
  schedule:
    # Runs Sunday and Wednesday at 09:00 UTC
    - cron: "0 9 * * 0,3"
  workflow_dispatch: {} # allow manual runs

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Curl ping with retries
        run: |
          set -e
          echo "Pinging $PING_URL"
          curl -I --retry 3 --retry-delay 5 --fail --max-time 20 "$PING_URL"
          echo "✅ Supabase ping OK"
        env:
          PING_URL: ${{ secrets.PING_URL }}
